apiVersion: kustomize.config.k8s.io/v1beta1
configMapGenerator:
- behavior: merge
  literals:
  - argoWorkflowsInsecure=true
  - cfHost=http://alexs-platform.ngrok.io
  - cors=http://alexs-platform.ngrok.io,http://local.codefresh.io
  - env=production
  - argoCdUrl=http://argocd-server:80
  - argoCdUsername=admin
  - password=t3mFiOUvFnqW6vjR
  name: cap-app-proxy-cm
kind: Kustomization
namespace: cf-local
resources:
- ../../base
- ingress.yaml
