apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: cf
  name: workflow-reporter
  namespace: cf-local
spec:
  eventBusName: codefresh-eventbus
  resource:
    workflows:
      eventTypes:
      - ADD
      - UPDATE
      - DELETE
      filter:
        createdBy: null
      group: argoproj.io
      namespace: cf-local
      resource: workflows
      version: v1alpha1
  template:
    container:
      name: ""
      resources: {}
    serviceAccountName: codefresh-sa
status: {}
